"""
Fitora - PDF generation.

Renders the diet chart (and could extend to the entry pass) as a downloadable
PDF using reportlab - no external service, no headless browser, generated
in-process from the same data the web view already shows.
"""
from __future__ import annotations
import io
from datetime import date
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate, Frame, KeepTogether, NextPageTemplate, PageBreak,
    PageTemplate, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

BRAND = colors.HexColor("#ED3311")
BRAND_LIGHT = colors.HexColor("#FFF3EF")
INK_900 = colors.HexColor("#16181d")
INK_500 = colors.HexColor("#657084")
INK_200 = colors.HexColor("#D5D9E0")


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "FitoraTitle", parent=base["Title"], fontSize=22, textColor=INK_900,
            spaceAfter=2, alignment=TA_LEFT, fontName="Helvetica-Bold",
        ),
        "subtitle": ParagraphStyle(
            "FitoraSubtitle", parent=base["Normal"], fontSize=11,
            textColor=BRAND, spaceAfter=14, fontName="Helvetica-Bold",
        ),
        "h2": ParagraphStyle(
            "FitoraH2", parent=base["Heading2"], fontSize=13, textColor=INK_900,
            spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold",
        ),
        "body": ParagraphStyle(
            "FitoraBody", parent=base["Normal"], fontSize=9.5,
            textColor=INK_900, leading=13.5,
        ),
        "muted": ParagraphStyle(
            "FitoraMuted", parent=base["Normal"], fontSize=8.5,
            textColor=INK_500, leading=12,
        ),
        "meal_slot": ParagraphStyle(
            "FitoraMealSlot", parent=base["Normal"], fontSize=10,
            textColor=BRAND, fontName="Helvetica-Bold", spaceAfter=3,
        ),
        "footer": ParagraphStyle(
            "FitoraFooter", parent=base["Normal"], fontSize=7.5,
            textColor=INK_500, alignment=TA_CENTER, leading=10,
        ),
    }


def _header_footer(canvas, doc):
    canvas.saveState()
    # top brand bar
    canvas.setFillColor(BRAND)
    canvas.rect(0, A4[1] - 8 * mm, A4[0], 8 * mm, stroke=0, fill=1)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(18 * mm, A4[1] - 6 * mm, "FITORA")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(A4[0] - 18 * mm, A4[1] - 6 * mm, "Personalised Diet Chart")
    # footer
    canvas.setFillColor(INK_500)
    canvas.setFont("Helvetica", 7)
    canvas.drawCentredString(
        A4[0] / 2, 10 * mm,
        f"Generated by Fitora on {date.today().strftime('%d %b %Y')} "
        f"- consult a doctor or dietitian before starting any new diet plan.",
    )
    canvas.setStrokeColor(INK_200)
    canvas.line(18 * mm, 14 * mm, A4[0] - 18 * mm, 14 * mm)
    canvas.restoreState()


def build_diet_chart_pdf(
    *,
    member_name: str,
    gym_name: str,
    membership_code: str,
    goal_label: str,
    targets: dict[str, Any],
    current_weight_kg: float | None,
    target_weight_kg: float | None,
    estimated_weeks_to_target: int | None,
    chart: dict[str, Any],
    tips: list[str],
    avoid: list[str],
    disclaimer: str,
) -> bytes:
    """Returns the finished PDF as raw bytes, ready to stream to the client."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=16 * mm, bottomMargin=18 * mm,
        leftMargin=18 * mm, rightMargin=18 * mm,
        title=f"Fitora Diet Chart - {member_name}",
    )
    s = _styles()
    story: list[Any] = []

    # ---------------------------------------------------------------- title
    story.append(Paragraph(f"{goal_label} Diet Plan", s["title"]))
    story.append(Paragraph(f"{member_name} &middot; {gym_name} &middot; {membership_code}", s["subtitle"]))

    # ------------------------------------------------------------ targets
    bmi_line = f"BMI {targets.get('bmi', '-')} ({targets.get('bmi_band', '-')})"
    weight_line = (
        f"{current_weight_kg} kg &rarr; {target_weight_kg} kg target"
        + (f" (~{estimated_weeks_to_target} weeks)" if estimated_weeks_to_target else "")
        if target_weight_kg else f"{current_weight_kg} kg"
    )

    stat_data = [
        ["Daily Calories", "Protein", "Carbs", "Fats", "Water"],
        [
            f"{targets.get('calories', '-')} kcal",
            f"{targets.get('protein_g', '-')} g",
            f"{targets.get('carbs_g', '-')} g",
            f"{targets.get('fats_g', '-')} g",
            f"{targets.get('water_litres', '-')} L",
        ],
    ]
    stat_table = Table(stat_data, colWidths=[32 * mm] * 5)
    stat_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), INK_900),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("BACKGROUND", (0, 1), (-1, 1), BRAND_LIGHT),
        ("TEXTCOLOR", (0, 1), (-1, 1), INK_900),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 1), (-1, 1), 11),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("BOX", (0, 0), (-1, -1), 0.5, INK_200),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, INK_200),
    ]))
    story.append(stat_table)
    story.append(Spacer(1, 4))
    story.append(Paragraph(f"{bmi_line} &middot; {weight_line}", s["muted"]))

    # ------------------------------------------------------------- meal chart
    story.append(Paragraph("Meal Plan", s["h2"]))
    for slot, info in chart.items():
        options = info.get("options", []) if isinstance(info, dict) else info
        block = [Paragraph(slot, s["meal_slot"])]
        for opt in options:
            block.append(Paragraph(f"&bull;&nbsp; {opt}", s["body"]))
        story.append(KeepTogether(block))
        story.append(Spacer(1, 6))

    # ------------------------------------------------------------------ tips
    story.append(Paragraph("Tips", s["h2"]))
    for t in tips:
        story.append(Paragraph(f"&#10003;&nbsp; {t}", s["body"]))

    story.append(Paragraph("Avoid", s["h2"]))
    for a in avoid:
        story.append(Paragraph(f"&times;&nbsp; {a}", s["body"]))

    story.append(Spacer(1, 10))
    story.append(Paragraph(disclaimer, s["muted"]))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buf.getvalue()
